name: trendbuy
description: "A shop app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  liquid_pull_to_refresh: ^3.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
      - family: samim
        fonts:
          - asset: assets/fonts/Samim-FD.ttf
          - asset: assets/fonts/Samim-Bold-FD.ttf
            weight: 700
          
        
